### PR TITLE
add optional clock to sytem tray via 'Toggle Clock' menu item

### PR DESCRIPTION
**Pull request by Flet**
clocksies

It relies exclusively on `clockmoji` to pick the icon to display, which shifts time forward 15 minutes by default for fuzziness (i.e. 5:50 PM will show the 6PM icon).

Also did a tiny bit of refactoring to get the icon updates in a single function... so `NativeImage.createEmpty()` is used when creating the tray.

I just pulled the clock icons from https://github.com/tmm1/emoji-extractor, and its just using the source icons directly. Were the @2x and @5x icons generated by you or pulled from somewhere?

At startup the clock is toggled off. If you like this we can continue to enhance it to possibly save the user's preference between runs :)

Hope things are going well for you, @bcomnes :)

### CODE REVIEW

**Comment by bcomnes** [comment]
Cool! Thanks so much.  Been busy with work and writing https://github.com/bcomnes/node-learnbook

**Comment by bcomnes** [comment]
Its important to get the sizing right on OS X, and I did the original work by hand.  Would be cool to streamline the process.

**Comment by Flet** [comment]
Looking at that GIF, I have no idea why the clock jumps from one side to the other when toggling :confused:

**Comment by bcomnes** [comment]
`¯\_(ツ)_/¯`  Also been massively distracted by https://github.com/bcomnes/ansible-arch-raspi

**Comment by Flet** [comment]
Hah, awesome :) I need to jump back into raspi stuff. Do you use ansible for work things?

`node-learnbook` looks super neat as well! I'll check it out this evening!

**Comment by bcomnes** [comment]
Been experimenting with it.  Its immediately useful as a remote execution engine which we used a bit for the PSU cluster.  Putting together individually reproducible systems takes a lot of time though.  You need to apply it ~3 times before you start making back your time investment into writing the plays IME.  Maybe it gets close to 1:1 eventually? I'm skeptical still.  About 4ish hours just to work through https://github.com/bcomnes/ansible-arch-raspi#ansible-pitfalls

**Pull request merged**
